#Hugo configuration
title = "sas"
baseURL = "https:\/\/sasas.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758904"
subfolder = ""
